/* Generated By:JavaCC: Do not edit this line. SQLParserTreeConstants.java Version 5.0 */
package com.pmitrofanov.db.sql;

public interface SQLParserTreeConstants
{
  public int JJTSQLSCRIPT = 0;
  public int JJTSQLSTATEMENT = 1;
  public int JJTSQLOPERATOR = 2;
  public int JJTQUERY = 3;
  public int JJTMODIFIER = 4;
  public int JJTASTERISK = 5;
  public int JJTSELECTLIST = 6;
  public int JJTSELECTEXPRESSION = 7;
  public int JJTFROMLIST = 8;
  public int JJTFROMLISTEXPRESSION = 9;
  public int JJTRELATION = 10;
  public int JJTNAMEDSUBQUERY = 11;
  public int JJTSUBQUERY = 12;
  public int JJTSINGLERELATION = 13;
  public int JJTRELATIONSPEC = 14;
  public int JJTSCHEMANAME = 15;
  public int JJTRELATIONNAME = 16;
  public int JJTJOINCLAUSE = 17;
  public int JJTINNERJOINSPEC = 18;
  public int JJTOUTERJOINSPEC = 19;
  public int JJTCROSSJOINSPEC = 20;
  public int JJTONCLAUSE = 21;
  public int JJTWHERECLAUSE = 22;
  public int JJTHAVINGCLAUSE = 23;
  public int JJTGROUPBYCLAUSE = 24;
  public int JJTGROUPBYLIST = 25;
  public int JJTGROUPBYEXPRESSION = 26;
  public int JJTORDERBYCLAUSE = 27;
  public int JJTORDERBYLIST = 28;
  public int JJTORDERBYEXPRESSION = 29;
  public int JJTLIMITCLAUSE = 30;
  public int JJTLIMITOFFSET = 31;
  public int JJTLIMITCOUNT = 32;
  public int JJTVALUEEXPRESSION = 33;
  public int JJTARITHMETICALOPERATOR = 34;
  public int JJTEQUALITYTEST = 35;
  public int JJTLOGICALTEST = 36;
  public int JJTNULLTEST = 37;
  public int JJTBETWEENTEST = 38;
  public int JJTPARENTHESIZEDEXPRESSION = 39;
  public int JJTOPERANDEXPRESSION = 40;
  public int JJTUNARYOPERATOR = 41;
  public int JJTUNARYOPERAND = 42;
  public int JJTFUNCTIONCALL = 43;
  public int JJTORDINARYFUNCTIONCALL = 44;
  public int JJTFUNCTIONNAME = 45;
  public int JJTARGLIST = 46;
  public int JJTAGGREGATEFUNCTIONCALL = 47;
  public int JJTBUILTINFUNCTIONCALL = 48;
  public int JJTCASTCALL = 49;
  public int JJTCONVERTCALL = 50;
  public int JJTEXISTSCALL = 51;
  public int JJTINTEST = 52;
  public int JJTCASECALL = 53;
  public int JJTSIMPLECASEEXPRESSION = 54;
  public int JJTSEARCHEDCASEEXPRESSION = 55;
  public int JJTWHENCLAUSES = 56;
  public int JJTWHENCLAUSE = 57;
  public int JJTWHENTEST = 58;
  public int JJTWHENOPTIONEXPRESSION = 59;
  public int JJTDEFAULTEXPRESSION = 60;
  public int JJTENCODINGNAME = 61;
  public int JJTARGUMENT = 62;
  public int JJTCOLUMNEXPRESSION = 63;
  public int JJTFULLYQUALIFIEDCOLUMNNAME = 64;
  public int JJTQUALIFIEDCOLUMNNAME = 65;
  public int JJTRELATIONNAMEORALIAS = 66;
  public int JJTUNQUALIFIEDCOLUMNNAME = 67;
  public int JJTCOLUMNNAME = 68;
  public int JJTALIAS = 69;
  public int JJTIDENTIFIER = 70;
  public int JJTSEARCHCONDITION = 71;
  public int JJTLITERAL = 72;
  public int JJTNUMERICORSTRINGLITERAL = 73;
  public int JJTBOOLEANLITERAL = 74;
  public int JJTNULLLITERAL = 75;
  public int JJTTYPE = 76;
  public int JJTNUMERICTYPE = 77;
  public int JJTSTRINGTYPE = 78;
  public int JJTBOOLEANTYPE = 79;
  public int JJTDATETIMETYPE = 80;


  public String[] jjtNodeName = {
    "SqlScript",
    "SqlStatement",
    "SqlOperator",
    "Query",
    "Modifier",
    "Asterisk",
    "SelectList",
    "SelectExpression",
    "FromList",
    "FromListExpression",
    "Relation",
    "NamedSubquery",
    "Subquery",
    "SingleRelation",
    "RelationSpec",
    "SchemaName",
    "RelationName",
    "JoinClause",
    "InnerJoinSpec",
    "OuterJoinSpec",
    "CrossJoinSpec",
    "OnClause",
    "WhereClause",
    "HavingClause",
    "GroupByClause",
    "GroupByList",
    "GroupByExpression",
    "OrderByClause",
    "OrderByList",
    "OrderByExpression",
    "LimitClause",
    "LimitOffset",
    "LimitCount",
    "ValueExpression",
    "ArithmeticalOperator",
    "EqualityTest",
    "LogicalTest",
    "NullTest",
    "BetweenTest",
    "ParenthesizedExpression",
    "OperandExpression",
    "UnaryOperator",
    "UnaryOperand",
    "FunctionCall",
    "OrdinaryFunctionCall",
    "FunctionName",
    "ArgList",
    "AggregateFunctionCall",
    "BuiltInFunctionCall",
    "CastCall",
    "ConvertCall",
    "ExistsCall",
    "InTest",
    "CaseCall",
    "SimpleCaseExpression",
    "SearchedCaseExpression",
    "WhenClauses",
    "WhenClause",
    "WhenTest",
    "WhenOptionExpression",
    "DefaultExpression",
    "EncodingName",
    "Argument",
    "ColumnExpression",
    "FullyQualifiedColumnName",
    "QualifiedColumnName",
    "RelationNameOrAlias",
    "UnqualifiedColumnName",
    "ColumnName",
    "Alias",
    "Identifier",
    "SearchCondition",
    "Literal",
    "NumericOrStringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Type",
    "NumericType",
    "StringType",
    "BooleanType",
    "DatetimeType",
  };
}
/* JavaCC - OriginalChecksum=58878ccec45f73718ac4be63ea072cdd (do not edit this line) */
